clusterGroup:
  name: resilient
  isHubCluster: false

  namespaces:
    - stackrox
    - openshift-storage
    - policies

  subscriptions:
    odf:
      name: odf-operator
      namespace: openshift-storage

  projects:
    - opp

  applications:
    storage:
      name: storage
      namespace: openshift-storage
      project: opp
      path: charts/hub/odf
